=== folio-org/mod-inventory-storage/ramls/schemas/instance-storage/instance.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "An instance record",
  "javaType": "org.folio.rest.jaxrs.model.Instance",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "The unique ID of the instance record; a UUID",
      "$ref": "../common/uuid.json"
    },
    "_version": {
      "type": "integer",
      "description": "Record version for optimistic locking"
    },
    "hrid": {
      "type": "string",
      "description": "The human readable ID, also called eye readable ID. A system-assigned sequential ID which maps to the Instance ID"
    },
    "matchKey": {
      "type": "string",
      "description": "A unique instance identifier matching a client-side bibliographic record identification scheme, in particular for a scenario where multiple separate catalogs with no shared record identifiers contribute to the same Instance in Inventory. A match key is typically generated from select, normalized pieces of metadata in bibliographic records"
    },
    "sourceUri": {
      "type": "string",
      "description": "A remote URI uniquely identifying the source of the instance"
    },
    "source": {
      "type": "string",
      "description": "The metadata source and its format of the underlying record to the instance record. (e.g. FOLIO if it's a record created in Inventory; MARC if it's a MARC record created in MARCcat or EPKB if it's a record coming from eHoldings; CONSORTIUM-MARC or CONSORTIUM-FOLIO for sharing Instances)."
    },
    "title": {
      "type": "string",
      "description": "The primary title (or label) associated with the resource"
    },
    "indexTitle": {
      "type": "string",
      "description": "Title normalized for browsing and searching; based on the title with articles removed"
    },
    "alternativeTitles": {
      "type": "array",
      "description": "List of alternative titles for the resource (e.g. original language version title of a movie)",
      "items": {
        "type": "object",
        "javaType": "org.folio.rest.jaxrs.model.AlternativeTitle",
        "properties": {
          "alternativeTitleTypeId": {
            "type": "string",
            "description": "UUID for an alternative title qualifier",
            "$ref": "../common/uuid.json"
          },
          "alternativeTitle": {
            "type": "string",
            "description": "An alternative title for the resource"
          },
          "authorityId": {
            "type": "string",
            "description": "UUID of authority record that controls an alternative title",
            "$ref": "../common/uuid.json"
          }
        }
      },
      "uniqueItems": true
    },
    "editions": {
      "type": "array",
      "description": "The edition statement, imprint and other publication source information",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "series": {
      "type": "array",
      "description": "List of series titles associated with the resource (e.g. Harry Potter)",
      "items": {
        "type": "object",
        "javaType": "org.folio.rest.jaxrs.model.SeriesItem",
        "properties": {
          "value": {
            "type": "string",
            "description": "Series title value"
          },
          "authorityId": {
            "type": "string",
            "description": "UUID of authority record that controls an series title",
            "$ref": "../common/uuid.json"
          }
        },
        "additionalProperties": false,
        "required": [
          "value"
        ]
      },
      "uniqueItems": true
    },
    "identifiers": {
      "type": "array",
      "description": "An extensible set of name-value pairs of identifiers associated with the resource",
      "minItems": 0,
      "items": {
        "type": "object",
        "javaType": "org.folio.rest.jaxrs.model.Identifier",
        "properties": {
          "value": {
            "type": "string",
            "description": "Resource identifier value"
          },
          "identifierTypeId": {
            "type": "string",
            "description": "UUID of resource identifier type (e.g. ISBN, ISSN, LCCN, CODEN, Locally defined identifiers)",
            "$ref": "../common/uuid.json"
          },
          "identifierTypeObject": {
            "type": "object",
            "description": "Information about identifier type, looked up from identifierTypeId",
            "javaType": "org.folio.rest.jaxrs.model.IdentifierTypeVirtual",
            "folio:$ref": "illpolicy.json",
            "readonly": true,
            "folio:isVirtual": true,
            "folio:linkBase": "identifier-types",
            "folio:linkFromField": "identifierTypeId",
            "folio:linkToField": "id",
            "folio:includedElement": "identifierTypes.0"
          }
        },
        "additionalProperties": false,
        "required": [
          "value",
          "identifierTypeId"
        ]
      }
    },
    "contributors": {
      "type": "array",
      "description": "List of contributors",
      "minItems": 0,
      "items": {
        "type": "object",
        "javaType": "org.folio.rest.jaxrs.model.Contributor",
        "properties": {
          "name": {
            "type": "string",
            "description": "Personal name, corporate name, meeting name"
          },
          "contributorTypeId": {
            "type": "string",
            "description": "UUID for the contributor type term defined in controlled vocabulary",
            "$ref": "../common/uuid.json"
          },
          "contributorTypeText": {
            "type": "string",
            "description": "Free text element for adding contributor type terms other that defined by the MARC code list for relators"
          },
          "contributorNameTypeId": {
            "type": "string",
            "description": "UUID of contributor name type term defined by the MARC code list for relators",
            "$ref": "../common/uuid.json"
          },
          "authorityId": {
            "type": "string",
            "description": "UUID of authority record that controls the contributor",
            "$ref": "../common/uuid.json"
          },
          "contributorNameType": {
            "type": "object",
            "description": "Dereferenced contributor-name type",
            "javaType": "org.folio.rest.jaxrs.model.ContributorNameTypeVirtual",
            "folio:$ref": "contributornametype.json",
            "readonly": true,
            "folio:isVirtual": true,
            "folio:linkBase": "contributor-name-types",
            "folio:linkFromField": "contributorNameTypeId",
            "folio:linkToField": "id",
            "folio:includedElement": "contributorNameTypes.0"
          },
          "primary": {
            "type": "boolean",
            "description": "Whether this is the primary contributor"
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "contributorNameTypeId"
        ]
      }
    },
    "subjects": {
      "type": "array",
      "description": "List of subject headings",
      "items": {
        "type": "object",
        "javaType": "org.folio.rest.jaxrs.model.Subject",
        "properties": {
          "value": {
            "type": "string",
            "description": "Subject heading value"
          },
          "authorityId": {
            "type": "string",
            "description": "UUID of authority record that controls a subject heading",
            "$ref": "../common/uuid.json"
          },
          "sourceId": {
            "type": "string",
            "description": "UUID of subject source",
            "$ref": "../common/uuid.json"
          },
          "typeId": {
            "type": "string",
            "description": "UUID of subject type",
            "$ref": "../common/uuid.json"
          }
        },
        "additionalProperties": false,
        "required": [
          "value"
        ]
      },
      "uniqueItems": true
    },
    "classifications": {
      "type": "array",
      "description": "List of classifications",
      "minItems": 0,
      "items": {
        "type": "object",
        "javaType": "org.folio.rest.jaxrs.model.Classification",
        "properties": {
          "classificationNumber": {
            "type": "string",
            "description": "Classification (e.g. classification scheme, classification schedule)"
          },
          "classificationTypeId": {
            "type": "string",
            "description": "UUID of classification schema (e.g. LC, Canadian Classification, NLM, National Agricultural Library, UDC, and Dewey)",
            "$ref": "../common/uuid.json"
          },
          "classificationType": {
            "type": "object",
            "description": "Dereferenced classification schema",
            "javaType": "org.folio.rest.jaxrs.model.ClassificationTypeVirtual",
            "folio:$ref": "classificationtype.json",
            "readonly": true,
            "folio:isVirtual": true,
            "folio:linkBase": "classification-types",
            "folio:linkFromField": "classificationTypeId",
            "folio:linkToField": "id",
            "folio:includedElement": "classificationTypes.0"
          }
        },
        "additionalProperties": false,
        "required": [
          "classificationNumber",
          "classificationTypeId"
        ]
      }
    },
    "publication": {
      "type": "array",
      "description": "List of publication items",
      "items": {
        "type": "object",
        "javaType": "org.folio.rest.jaxrs.model.PublicationItem",
        "properties": {
          "publisher": {
            "type": "string",
            "description": "Name of publisher, distributor, etc."
          },
          "place": {
            "type": "string",
            "description": "Place of publication, distribution, etc."
          },
          "dateOfPublication": {
            "type": "string",
            "description": "Date (year YYYY) of publication, distribution, etc."
          },
          "role": {
            "type": "string",
            "description": "The role of the publisher, distributor, etc."
          }
        }
      }
    },
    "publicationFrequency": {
      "type": "array",
      "description": "List of intervals at which a serial appears (e.g. daily, weekly, monthly, quarterly, etc.)",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "publicationRange": {
      "type": "array",
      "description": "The range of sequential designation/chronology of publication, or date range",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "electronicAccess": {
      "type": "array",
      "description": "List of electronic access items",
      "items": {
        "type": "object",
        "$ref": "../common/electronicAccessItem.json"
      }
    },
    "dates": {
      "type": "object",
      "description": "Instance Dates",
      "javaType": "org.folio.rest.jaxrs.model.InstanceDates",
      "properties": {
        "dateTypeId": {
          "type": "string",
          "description": "Date type ID",
          "$ref": "../common/uuid.json"
        },
        "date1": {
          "type": "string",
          "description": "Date 1",
          "maxLength": 4
        },
        "date2": {
          "type": "string",
          "description": "Date 2",
          "maxLength": 4
        }
      },
      "additionalProperties": false
    },
    "instanceTypeId": {
      "type": "string",
      "description": "UUID of the unique term for the resource type whether it's from the RDA content term list of locally defined",
      "$ref": "../common/uuid.json"
    },
    "instanceFormatIds": {
      "type": "array",
      "description": "UUIDs for the unique terms for the format whether it's from the RDA carrier term list of locally defined",
      "items": {
        "type": "string",
        "$ref": "../common/uuid.json"
      }
    },
    "instanceFormats": {
      "type": "array",
      "description": "List of dereferenced instance formats",
      "items": {
        "type": "object",
        "$ref": "../instance-formats/instanceformat.json"
      },
      "readonly": true,
      "folio:isVirtual": true,
      "folio:linkBase": "instance-formats",
      "folio:linkFromField": "instanceFormatIds",
      "folio:linkToField": "id",
      "folio:includedElement": "instanceFormats"
    },
    "physicalDescriptions": {
      "type": "array",
      "description": "Physical description of the described resource, including its extent, dimensions, and such other physical details as a description of any accompanying materials and unit type and size",
      "items": {
        "type": "string"
      }
    },
    "languages": {
      "type": "array",
      "description": "The set of languages used by the resource",
      "minItems": 0,
      "items": {
        "type": "string"
      }
    },
    "notes": {
      "type": "array",
      "description": "Bibliographic notes (e.g. general notes, specialized notes)",
      "items": {
        "type": "object",
        "javaType": "org.folio.rest.jaxrs.model.InstanceNote",
        "additionalProperties": false,
        "properties": {
          "instanceNoteTypeId": {
            "description": "ID of the type of note",
            "$ref": "../common/uuid.json"
          },
          "note": {
            "type": "string",
            "description": "Text content of the note"
          },
          "staffOnly": {
            "type": "boolean",
            "description": "If true, determines that the note should not be visible for others than staff",
            "default": false
          }
        }
      }
    },
    "administrativeNotes": {
      "type": "array",
      "description": "Administrative notes",
      "minItems": 0,
      "items": {
        "type": "string"
      }
    },
    "modeOfIssuanceId": {
      "type": "string",
      "description": "UUID of the RDA mode of issuance, a categorization reflecting whether a resource is issued in one or more parts, the way it is updated, and whether its termination is predetermined or not (e.g. monograph,  sequential monograph, serial; integrating Resource, other)",
      "$ref": "../common/uuid.json"
    },
    "catalogedDate": {
      "type": "string",
      "description": "Date or timestamp on an instance for when is was considered cataloged"
    },
    "previouslyHeld": {
      "type": "boolean",
      "description": "Records the fact that the resource was previously held by the library for things like Hathi access, etc.",
      "default": false
    },
    "staffSuppress": {
      "type": "boolean",
      "description": "Records the fact that the record should not be displayed for others than catalogers"
    },
    "discoverySuppress": {
      "type": "boolean",
      "description": "Records the fact that the record should not be displayed in a discovery system",
      "default": false
    },
    "deleted": {
      "type": "boolean",
      "description": "Indicates whether the record was marked for deletion",
      "default": false
    },
    "statisticalCodeIds": {
      "type": "array",
      "description": "List of statistical code IDs",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "sourceRecordFormat": {
      "type": "string",
      "description": "Format of the instance source record, if a source record exists (e.g. FOLIO if it's a record created in Inventory,  MARC if it's a MARC record created in MARCcat or EPKB if it's a record coming from eHoldings)",
      "enum": [
        "MARC-JSON"
      ],
      "readonly": true
    },
    "statusId": {
      "type": "string",
      "description": "UUID for the Instance status term (e.g. cataloged, uncatalogued, batch loaded, temporary, other, not yet assigned)",
      "$ref": "../common/uuid.json"
    },
    "statusUpdatedDate": {
      "type": "string",
      "description": "Date [or timestamp] for when the instance status was updated"
    },
    "tags": {
      "description": "arbitrary tags associated with this instance",
      "id": "tags",
      "type": "object",
      "$ref": "../../raml-util/schemas/tags.schema"
    },
    "metadata": {
      "type": "object",
      "$ref": "../../raml-util/schemas/metadata.schema",
      "readonly": true
    },
    "holdingsRecords2": {
      "type": "array",
      "description": "List of holdings records",
      "items": {
        "type": "object",
        "$ref": "../holdings-storage/holdingsRecord.json"
      },
      "readonly": true,
      "folio:isVirtual": true,
      "folio:linkBase": "holdings-storage/holdings",
      "folio:linkFromField": "id",
      "folio:linkToField": "instanceId",
      "folio:includedElement": "holdingsRecords"
    },
    "natureOfContentTermIds": {
      "type": "array",
      "description": "Array of UUID for the Instance nature of content (e.g. bibliography, biography, exhibition catalogue, festschrift, newspaper, proceedings, research report, thesis or website)",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "description": "Single UUID for the Instance nature of content",
        "$ref": "../common/uuid.json"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "source",
    "title",
    "instanceTypeId"
  ]
}

=== folio-org/mod-inventory-storage/sample-data/instances/dc-motor-control-experiment.json
{
  "id": "6eee8eb9-db1a-46e2-a8ad-780f19974efa",
  "source": "MARC",
  "title": "DC Motor Control Experiment Objekt for introduction to control systems Herbert Werner",
  "alternativeTitles": [],
  "series": [],
  "identifiers": [
    {
      "value": "727867881",
      "identifierTypeId": "5d164f4b-0b15-4e42-ae75-cfcf85318ad9"
    },
    {
      "value": "(DE-599)GBV727867881",
      "identifierTypeId": "7e591197-f335-4afb-bc6d-a6d76ca3bace"
    }
  ],
  "contributors": [
    {
      "contributorNameTypeId": "2b94c631-fca9-4892-a730-03ee529ffe2a",
      "name": "Werner, Herbert"
    },
    {
      "contributorNameTypeId": "2e48e713-17f3-4c13-a9f8-23845bb210aa",
      "name": "Technische Universität Hamburg-Harburg Institut für Regelungstechnik"
    }
  ],
  "subjects": [],
  "classifications": [],
  "publication": [
    {
      "publisher": "Techn. Univ., Inst. für Regelungstechnik",
      "place": "Hamburg",
      "dateOfPublication": "[2016]"
    }
  ],
  "instanceTypeId": "c1e95c2b-4efc-48cf-9e71-edb622cf0c22",
  "physicalDescriptions": [
    "1 Koffer (Inhalt: 1 Motor mit Platine auf Plattform, 1 Netzteil, 1 USB-Kabel)"
  ],
  "languages": [
    "ger"
  ],
  "notes": []
}

=== folio-org/mod-inventory-storage/sample-data/instances/nod.json
{
  "id": "6506b79b-7702-48b2-9774-a1c538fdd34e",
  "source": "MARC",
  "title": "Nod",
  "contributors": [
    {
      "contributorNameTypeId": "2b94c631-fca9-4892-a730-03ee529ffe2a",
      "name": "Barnes, Adrian"
    }
  ],
  "identifiers": [
    {
      "identifierTypeId": "8261054f-be78-422d-bd51-4ed9f33c3422",
      "value": "0956687695"
    },
    {
      "identifierTypeId": "8261054f-be78-422d-bd51-4ed9f33c3422",
      "value": "9780956687695"
    }
  ],
  "instanceTypeId": "6312d172-f0cf-40f6-b27d-9fa8feaf332f"
}

=== folio-org/mod-inventory-storage/sample-data/instances/signature-of-complex-system.json
{
  "id": "54cc0262-76df-4cac-acca-b10e9bc5c79a",
  "source": "MARC",
  "title": "On the signature of complex system a decomposed approach Gaofeng Da, Ping Shing Chan, Maochao Xu",
  "alternativeTitles": [],
  "series": [],
  "identifiers": [
    {
      "value": "1011184508",
      "identifierTypeId": "5d164f4b-0b15-4e42-ae75-cfcf85318ad9"
    },
    {
      "value": "(DE-599)GBV1011184508",
      "identifierTypeId": "7e591197-f335-4afb-bc6d-a6d76ca3bace"
    }
  ],
  "contributors": [
    {
      "contributorNameTypeId": "2b94c631-fca9-4892-a730-03ee529ffe2a",
      "name": "Da, Gaofeng"
    },
    {
      "contributorNameTypeId": "2b94c631-fca9-4892-a730-03ee529ffe2a",
      "name": "Chan, Ping Shing"
    },
    {
      "contributorNameTypeId": "2b94c631-fca9-4892-a730-03ee529ffe2a",
      "name": "Xu, Maochao"
    }
  ],
  "subjects": [],
  "classifications": [],
  "publication": [],
  "instanceTypeId": "6312d172-f0cf-40f6-b27d-9fa8feaf332f",
  "physicalDescriptions": [],
  "languages": [
    "eng"
  ],
  "notes": []
}

=== folio-org/mod-inventory-storage/src/test/resources/instances/bulk/expectedInstance.json
{
  "id": "0079916b-7b70-41d6-8c2d-3282b4f2e3d2",
  "_version": 1,
  "hrid": "in00001",
  "source": "MARC",
  "matchKey": "1579450",
  "title": "The Journal of ecclesiastical history.",
  "indexTitle": "Journal of ecclesiastical history.",
  "alternativeTitles": [
    {
      "alternativeTitleTypeId": "fe19bae4-da28-472b-be90-d442e2428ead",
      "alternativeTitle": "Herpetological conservation and biology (Online)"
    },
    {
      "alternativeTitleTypeId": "fe19bae4-da28-472b-be90-d442e2428ead",
      "alternativeTitle": "HCB"
    },
    {
      "alternativeTitleTypeId": "fe19bae4-da28-472b-be90-d442e2428ead",
      "alternativeTitle": "testingAlternativeTitle"
    }
  ],
  "editions": [
    "1st Ballantine Books trade pbk. ed."
  ],
  "series": [
    {
      "value": "Smithsonian global sound for libraries."
    }
  ],
  "identifiers": [
    {
      "value": "58020553",
      "identifierTypeId": "fe19bae4-da28-472b-be90-d442e2428ead"
    },
    {
      "value": "0022-0469",
      "identifierTypeId": "fe19bae4-da28-472b-be90-d442e2428ead"
    },
    {
      "value": "(CStRLIN)NYCX1604275S",
      "identifierTypeId": "fe19bae4-da28-472b-be90-d442e2428ead"
    },
    {
      "value": "(NIC)notisABP6388",
      "identifierTypeId": "fe19bae4-da28-472b-be90-d442e2428ead"
    },
    {
      "value": "366832",
      "identifierTypeId": "fe19bae4-da28-472b-be90-d442e2428ead"
    },
    {
      "value": "(OCoLC)1604275",
      "identifierTypeId": "fe19bae4-da28-472b-be90-d442e2428ead"
    }
  ],
  "contributors": [
    {
      "name": "Dugmore, C. W. (Clifford William)",
      "contributorTypeText": "ed.",
      "contributorNameTypeId": "fe19bae4-da28-472b-be90-d442e2428ead",
      "primary": false
    }
  ],
  "subjects": [
    {
      "value": "Church history--Periodicals"
    },
    {
      "value": "Church history"
    },
    {
      "value": "Periodicals"
    }
  ],
  "classifications": [
    {
      "classificationNumber": "BR140 .J6",
      "classificationTypeId": "fe19bae4-da28-472b-be90-d442e2428ead"
    },
    {
      "classificationNumber": "270.05",
      "classificationTypeId": "fe19bae4-da28-472b-be90-d442e2428ead"
    }
  ],
  "publication": [
    {
      "publisher": "Cambridge University Press [etc.]",
      "place": "London"
    }
  ],
  "publicationFrequency": [
    "Quarterly, 1970-",
    "Semiannual, 1950-69"
  ],
  "publicationRange": [
    "v. 1-   Apr. 1950-"
  ],
  "electronicAccess": [
    {
      "uri": "http://resolver.library.cornell.edu/cgi-bin/EADresolver?id=RMA01776",
      "materialsSpecification": "Finding aid",
      "relationshipId": "fe19bae4-da28-472b-be90-d442e2428ead"
    }
  ],
  "instanceTypeId": "fe19bae4-da28-472b-be90-d442e2428ead",
  "instanceFormatIds": [
    "5cb91d15-96b1-4b8a-bf60-ec310538da66"
  ],
  "physicalDescriptions": [
    "v. 25 cm."
  ],
  "languages": [
    "eng"
  ],
  "notes": [
    {
      "instanceNoteTypeId": "fe19bae4-da28-472b-be90-d442e2428ead",
      "note": "Includes index",
      "staffOnly": false
    }
  ],
  "administrativeNotes": [],
  "modeOfIssuanceId": "09314e47-4609-42e4-8fe5-a22cecc368bc",
  "catalogedDate": "2020-08-17",
  "previouslyHeld": true,
  "staffSuppress": false,
  "discoverySuppress": true,
  "statisticalCodeIds": [
    "53d5c842-67c1-4035-9964-29b25897222f"
  ],
  "sourceRecordFormat": "MARC-JSON",
  "statusId": "52a2ff34-2a12-420d-8539-21aa8d3cf5d8",
  "statusUpdatedDate": "1970-01-01T12:07:47.602+0000",
  "tags": {
    "tagList": [
      "important"
    ]
  },
  "natureOfContentTermIds": [
    "96879b60-098b-453b-bf9a-c47866f1ab2a"
  ]
}

=== folio-org/mod-inventory-storage/sample-data/bound-with/instances-25.1/instance_magazine_q2.json
{
  "id" : "858b9600-bd76-44ff-a83e-f82dcf5ed12b",
  "hrid" : "bwinst0005",
  "source" : "FOLIO",
  "title" : "Magazine - Q2",
  "identifiers" : [ {
    "identifierTypeId" : "2e8b3b6c-0e7d-4e48-bca2-b0b23b376af5",
    "value" : "bw"
  } ],
  "instanceTypeId" : "6312d172-f0cf-40f6-b27d-9fa8feaf332f",
  "previouslyHeld" : false,
  "staffSuppress" : false,
  "discoverySuppress" : false,
  "statusUpdatedDate" : "2022-10-12T13:04:17.905+0000"
}
