=== folio-org/mod-inventory-storage/ramls/authorities/authority.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "An authority record",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Authority UUID",
      "$ref": "../uuid.json"
    },
    "_version": {
      "type": "integer",
      "description": "Record version for optimistic locking"
    },
    "source": {
      "type": "string",
      "description": "The metadata source of the underlying record to the authority record. (e.g. FOLIO if it's a record created in Inventory;  MARC if it's a MARC record created in data-import)",
      "enum": ["MARC", "FOLIO"],
      "readonly": true
    },
    "personalName": {
      "type": "string",
      "description": "Heading personal name"
    },
    "sftPersonalName": {
      "type": "array",
      "description": "See from tracing personal name",
      "items": {
        "type": "string"
      }
    },
    "saftPersonalName": {
      "type": "array",
      "description": "See also from tracing personal name",
      "items": {
        "type": "string"
      }
    },
    "personalNameTitle": {
      "type": "string",
      "description": "Heading personal name title"
    },
    "sftPersonalNameTitle": {
      "type": "array",
      "description": "See from tracing personal name title",
      "items": {
        "type": "string"
      }
    },
    "saftPersonalNameTitle": {
      "type": "array",
      "description": "See also from tracing personal name title",
      "items": {
        "type": "string"
      }
    },
    "corporateName": {
      "type": "string",
      "description": "Heading corporate name"
    },
    "sftCorporateName": {
      "type": "array",
      "description": "See from tracing corporate name",
      "items": {
        "type": "string"
      }
    },
    "saftCorporateName": {
      "type": "array",
      "description": "See also from tracing corporate name",
      "items": {
        "type": "string"
      }
    },
    "corporateNameTitle": {
      "type": "string",
      "description": "Heading corporate name title"
    },
    "sftCorporateNameTitle": {
      "type": "array",
      "description": "See from tracing corporate name title",
      "items": {
        "type": "string"
      }
    },
    "saftCorporateNameTitle": {
      "type": "array",
      "description": "See also from tracing corporate name title",
      "items": {
        "type": "string"
      }
    },
    "meetingName": {
      "type": "string",
      "description": "Heading meeting name"
    },
    "sftMeetingName": {
      "type": "array",
      "description": "See from tracing meeting name",
      "items": {
        "type": "string"
      }
    },
    "saftMeetingName": {
      "type": "array",
      "description": "See also from tracing meeting name",
      "items": {
        "type": "string"
      }
    },
    "meetingNameTitle": {
      "type": "string",
      "description": "Heading meeting name title"
    },
    "sftMeetingNameTitle": {
      "type": "array",
      "description": "See from tracing meeting name title",
      "items": {
        "type": "string"
      }
    },
    "saftMeetingNameTitle": {
      "type": "array",
      "description": "See also from tracing meeting name title",
      "items": {
        "type": "string"
      }
    },
    "uniformTitle": {
      "type": "string",
      "description": "Heading uniform title"
    },
    "sftUniformTitle": {
      "type": "array",
      "description": "See from tracing uniform title",
      "items": {
        "type": "string"
      }
    },
    "saftUniformTitle": {
      "type": "array",
      "description": "See also from tracing uniform title",
      "items": {
        "type": "string"
      }
    },
    "topicalTerm": {
      "type": "string",
      "description": "Heading topical term"
    },
    "sftTopicalTerm": {
      "type": "array",
      "description": "See from tracing topical term",
      "items": {
        "type": "string"
      }
    },
    "saftTopicalTerm": {
      "type": "array",
      "description": "See also from tracing topical term",
      "items": {
        "type": "string"
      }
    },
    "subjectHeadings": {
      "type": "string",
      "description": "Children's subject headings"
    },
    "geographicName": {
      "type": "string",
      "description": "Heading geographic name"
    },
    "sftGeographicTerm": {
      "type": "array",
      "description": "See from tracing geographic name",
      "items": {
        "type": "string"
      }
    },
    "saftGeographicTerm": {
      "type": "array",
      "description": "See also from tracing geographic name",
      "items": {
        "type": "string"
      }
    },
    "genreTerm": {
      "type": "string",
      "description": "Heading genre/form term"
    },
    "sftGenreTerm": {
      "type": "array",
      "description": "See from tracing genre/form term",
      "items": {
        "type": "string"
      }
    },
    "saftGenreTerm": {
      "type": "array",
      "description": "See also from tracing genre/form term",
      "items": {
        "type": "string"
      }
    },
    "identifiers": {
      "type": "array",
      "description": "An extensible set of name-value pairs of identifiers associated with the resource",
      "items": {
        "type": "object",
        "properties": {
          "value": {
            "type": "string",
            "description": "Resource identifier value"
          },
          "identifierTypeId": {
            "type": "string",
            "description": "Resource identifier type (e.g. Control number, LCCN, Other standard identifier, System control number)",
            "$ref": "../uuid.json"
          }
        },
        "required": [
          "value",
          "identifierTypeId"
        ]
      }
    },
    "notes": {
      "type": "array",
      "description": "Notes (e.g. nonpublic general note)",
      "items": {
        "type": "object",
        "properties": {
          "noteTypeId": {
            "description": "ID of the type of note",
            "$ref": "../uuid.json"
          },
          "note": {
            "type": "string",
            "description": "Text content of the note"
          }
        },
        "required": [
          "note",
          "noteTypeId"
        ]
      }
    },
    "metadata": {
      "type": "object",
      "description": "Creater, updater, creation date, last updated date",
      "$ref": "../raml-util/schemas/metadata.schema"
    }
  },
  "additionalProperties": false
}

=== folio-org/mod-inventory-storage/sample-data/authorities/auth4.json
{
  "id": "8187ae0a-e8cf-4876-b00a-ae4f839de8bf",
  "personalName": "Mark, Barbara. Angelspeake book of prayer and healing. Spanish",
  "sftPersonalName": [
    "Mark, Barbara. Devocionario de su angel de la guarda"
  ],
  "saftPersonalName": [],
  "sftPersonalNameTitle": [],
  "saftPersonalNameTitle": [],
  "sftCorporateName": [],
  "saftCorporateName": [],
  "sftCorporateNameTitle": [],
  "saftCorporateNameTitle": [],
  "sftMeetingName": [],
  "saftMeetingName": [],
  "sftMeetingNameTitle": [],
  "saftMeetingNameTitle": [],
  "sftUniformTitle": [],
  "saftUniformTitle": [],
  "sftTopicalTerm": [],
  "saftTopicalTerm": [],
  "subjectHeadings": "c",
  "sftGeographicTerm": [],
  "saftGeographicTerm": [],
  "sftGenreTerm": [],
  "saftGenreTerm": [],
  "identifiers": [
    {
      "value": "877751",
      "identifierTypeId": "6051f95c-028e-4c6a-8a9e-ee689dd51453"
    },
    {
      "value": "n  97095655 ",
      "identifierTypeId": "e8b311a6-3b21-43f2-a269-dd9310cb2d0f"
    },
    {
      "value": "(DLC)n  97095655",
      "identifierTypeId": "e8b311a6-3b21-43f2-a269-dd9310cb2d0f"
    }
  ],
  "notes": []
}
