=== folio-org/mod-inventory-storage/ramls/schemas/locations/location.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "A (shelf) location, the forth-level location unit below institution, campus, and library.",
  "javaType": "org.folio.rest.jaxrs.model.Location",
  "type": "object",
  "properties": {
    "id": {
      "description": "id of this (shelf) location record as UUID.",
      "type": "string"
    },
    "name": {
      "description": "Name of the (shelf) location",
      "type": "string"
    },
    "code": {
      "description": "Code of the (shelf) location, usually an abbreviation of the name.",
      "type": "string"
    },
    "description": {
      "description": "Description of the (shelf) location.",
      "type": "string"
    },
    "discoveryDisplayName": {
      "description": "Name of the (shelf) location to be shown in the discovery.",
      "type": "string"
    },
    "isActive": {
      "description": "Whether this (shelf) location is active. Inactive (shelf) locations can no longer been used.",
      "type": "boolean"
    },
    "institutionId": {
      "description": "The UUID of the institution, the first-level location unit, this (shelf) location belongs to.",
      "type": "string"
    },
    "institution": {
      "description": "The institution, the first-level location unit, this (shelf) location belongs to.",
      "type": "object",
      "folio:$ref": "locinst.json",
      "javaType": "org.folio.rest.jaxrs.model.InstitutionVirtual",
      "readonly": true,
      "folio:isVirtual": true,
      "folio:linkBase": "location-units/institutions",
      "folio:linkFromField": "institutionId",
      "folio:linkToField": "id",
      "folio:includedElement": "locinsts.0"
    },
    "campusId": {
      "description": "The UUID of the campus, the second-level location unit, this (shelf) location belongs to.",
      "type": "string"
    },
    "campus": {
      "description": "The campus, the second-level location unit, this (shelf) location belongs to",
      "type": "object",
      "javaType": "org.folio.rest.jaxrs.model.CampusVirtual",
      "folio:$ref": "loccamp.json",
      "readonly": true,
      "folio:isVirtual": true,
      "folio:linkBase": "location-units/campuses",
      "folio:linkFromField": "campusId",
      "folio:linkToField": "id",
      "folio:includedElement": "loccamps.0"
    },
    "libraryId": {
      "description": "The UUID of the library, the third-level location unit, this (shelf) location belongs to.",
      "type": "string"
    },
    "library": {
      "description": "The library, the third-level location unit, this (shelf) location belongs to.",
      "type": "object",
      "javaType": "org.folio.rest.jaxrs.model.LibraryVirtual",
      "folio:$ref": "locinst.json",
      "readonly": true,
      "folio:isVirtual": true,
      "folio:linkBase": "location-units/libraries",
      "folio:linkFromField": "libraryId",
      "folio:linkToField": "id",
      "folio:includedElement": "loclibs.0"
    },
    "details": {
      "description": "Details about this (shelf) location.",
      "type": "object",
      "javaType": "org.folio.rest.jaxrs.model.LocationDetails"
    },
    "primaryServicePoint": {
      "description": "The UUID of the primary service point of this (shelf) location.",
      "format": "uuid",
      "type": "string"
    },
    "primaryServicePointObject": {
      "type": "object",
      "description": "Dereferenced object for primary service point. This should really just be called 'primaryServicePoint', but the field containing the ID of this object has that name -- it should really be called 'primaryServicePointId' -- so we need something different for this one.",
      "$ref": "../service-points/servicepoint.json",
      "javaType": "org.folio.rest.jaxrs.model.ServicePointVirtual",
      "readonly": true,
      "folio:isVirtual": true,
      "folio:linkBase": "service-points",
      "folio:linkFromField": "primaryServicePoint",
      "folio:linkToField": "id",
      "folio:includedElement": "servicepoints.0"
    },
    "servicePointIds": {
      "description": "All service points that this (shelf) location has.",
      "type": "array",
      "items": {
        "description": "The UUID of a service point that belongs to this (shelf) location.",
        "type": "string",
        "format": "uuid",
        "not": {
          "type": "null"
        }
      }
    },
    "isFloatingCollection": {
      "description": "Items checked in/out from this location can be checked in/out to other locations with the same flag.",
      "type": "boolean"
    },
    "servicePoints": {
      "type": "array",
      "description": "List of dereferenced service points",
      "items": {
        "type": "object",
        "$ref": "../service-points/servicepoint.json"
      },
      "readonly": true,
      "folio:isVirtual": true,
      "folio:linkBase": "service-points",
      "folio:linkFromField": "servicePointIds",
      "folio:linkToField": "id",
      "folio:includedElement": "servicepoints"
    },
    "isShadow": {
      "description": "Whether this location is a shadow location. Shadow locations are used to represent virtual locations that no items are assignable to them. They only relate to external libraries and virtual items.",
      "type": "boolean",
      "default": false
    },
    "metadata": {
      "type": "object",
      "$ref": "../../raml-util/schemas/metadata.schema",
      "readonly": true
    }
  },
  "additionalProperties": false,
  "required": [
    "name",
    "code",
    "institutionId",
    "campusId",
    "libraryId",
    "primaryServicePoint"
  ]
}

=== folio-org/mod-inventory-storage/sample-data/locations/orwig-ethno-cd.json
{
  "id": "758258bc-ecc1-41b8-abca-f7b610822ffd",
  "name": "ORWIG ETHNO CD",
  "code": "KU/CC/DI/O",
  "isActive": true,
  "institutionId": "40ee00ca-a518-4b49-be01-0638d0a4ac57",
  "campusId": "62cf76b7-cca5-4d33-9217-edf42ce1a848",
  "libraryId": "5d78803e-ca04-4b4a-aeae-2c63b924518b",
  "primaryServicePoint": "3a40852d-49fd-4df2-a1f9-6e2641a6e91f",
  "servicePointIds": [ "3a40852d-49fd-4df2-a1f9-6e2641a6e91f" ]
}
