=== folio-org/mod-inventory-storage/src/test/resources/schema/item.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "An item record",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique ID of the item record"
    },
    "hrid": {
      "type": "string",
      "description": "The human readable ID, also called eye readable ID. A system-assigned sequential alternate ID"
    },
    "holdingsRecordId": {
      "type": "string"
    },
    "formerIds": {
      "type": "array",
      "description": "Previous identifiers assigned to the item",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "discoverySuppress": {
      "type": "boolean",
      "description": "Records the fact that the record should not be displayed in a discovery system"
    },
    "accessionNumber": {
      "type": "string",
      "description": "Also called inventar number"
    },
    "barcode": {
      "type": "string"
    },
    "itemLevelCallNumber": {
      "type": "string"
    },
    "itemLevelCallNumberPrefix": {
      "type": "string"
    },
    "itemLevelCallNumberSuffix": {
      "type": "string"
    },
    "itemLevelCallNumberTypeId": {
      "type": "string"
    },
    "volume": {
      "type": "string"
    },
    "enumeration": {
      "type": "string"
    },
    "chronology": {
      "type": "string"
    },
    "yearCaption": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "itemIdentifier": {
      "type": "string"
    },
    "copyNumbers": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "numberOfPieces": {
      "type": "string"
    },
    "descriptionOfPieces": {
      "type": "string"
    },
    "numberOfMissingPieces": {
      "type": "string"
    },
    "missingPieces": {
      "type": "string"
    },
    "missingPiecesDate": {
      "type": "string"
    },
    "itemDamagedStatusId": {
      "type": "string"
    },
    "itemDamagedStatusDate": {
      "type": "string"
    },
    "notes": {
      "type": "array",
      "description": "Notes about action, copy, binding etc.",
      "items": {
        "type": "object",
        "properties": {
          "itemNoteTypeId": {
            "type": "string",
            "description": "ID of the type of note"
          },
          "note": {
            "type": "string",
            "description": "Text content of the note"
          },
          "staffOnly": {
            "type": "boolean",
            "description": "If true, determines that the note should not be visible for others than staff",
            "default": false
          }
        }
      }
    },
    "circulationNotes": {
      "type": "array",
      "description": "Notes to be displayed in circulation processes",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "The id of the circulation note"
          },
          "noteType": {
            "type": "string",
            "description": "Type of circulation process that the note applies to",
            "enum": ["Check in", "Check out"]
          },
          "note": {
            "type": "string",
            "description": "Text to display"
          },
          "source": {
            "type": "object",
            "description": "The user who added/updated the note. The property is generated by the server and needed to support sorting. Points to /users/{id} resource.",
            "properties": {
              "id": {
                "type": "string",
                "description": "The id of the user who added/updated the note. The user information is generated by the server and needed to support sorting. Points to /users/{id} resource."
              },
              "personal": {
                "type": "object",
                "description": "Personal information about the user",
                "properties": {
                  "lastName": {
                    "description": "The user's last name",
                    "type": "string"
                  },
                  "firstName": {
                    "description": "The user's first name",
                    "type": "string"
                  }
                }
              }
            }
          },
          "date": {
            "type": "string",
            "description": "Date and time the record is added/updated. The property is generated by the server and needed to support sorting."
          },
          "staffOnly": {
            "type": "boolean",
            "default": "Flag to restrict display of this note",
            "default": false
          }
        },
        "additionalProperties": false
      }
    },
    "status": {
      "description": "The status of the item",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the status e.g. Available, Checked out, In transit",
          "type": "string"
        },
        "date": {
          "description": "Date of a status",
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "materialTypeId": {
      "type": "string"
    },
    "permanentLoanTypeId": {
      "type": "string"
    },
    "temporaryLoanTypeId": {
      "type": "string"
    },
    "permanentLocationId": {
      "type": "string"
    },
    "temporaryLocationId": {
      "type": "string"
    },
    "electronicAccess": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "uri": {
            "type": "string",
            "description": "uniform resource identifier (URI) is a string of characters designed for unambiguous identification of resources"
          },
          "linkText": {
            "type": "string",
            "description": "the value of the MARC tag field 856 2nd indicator, where the values are: no information provided, resource, version of resource, related resource, no display constant generated"
          },
          "materialsSpecification": {
            "type": "string",
            "description": "materials specified is used to specify to what portion or aspect of the resource the electronic location and access information applies (e.g. a portion or subset of the item is electronic, or a related electronic resource is being linked to the record)"
          },
          "publicNote": {
            "type": "string",
            "description": "URL public note to be displayed in the discovery"
          },
          "relationshipId": {
            "type": "string",
            "description": "relationship between the electronic resource at the location identified and the item described in the record as a whole"
          }
        },
        "additionalProperties": false,
        "required": [
          "uri"
        ]
      }
    },
    "inTransitDestinationServicePointId": {
      "description": "Service point an item is intended to be transited to (should only be present when in transit)",
      "type": "string",
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
    },
    "statisticalCodeIds": {
      "type": "array",
      "description": "List of statistical code IDs",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "purchaseOrderLineIdentifier": {
      "type": "string",
      "description": "ID referencing a remote purchase order object related to this item"
    },
    "tags": {
      "description": "arbitrary tags associated with this item",
      "id": "tags",
      "type": "object",
      "$ref": "raml-util/schemas/tags.schema"
    },
    "metadata": {
      "type": "object",
      "$ref": "raml-util/schemas/metadata.schema",
      "readonly": true
    },
    "holdingsRecord2": {
      "type": "object",
      "folio:$ref": "holdingsrecord.json",
      "readonly": true,
      "folio:isVirtual": true,
      "folio:linkBase": "holdings-storage/holdings",
      "folio:linkFromField": "holdingsRecordId",
      "folio:linkToField": "id",
      "folio:includedElement": "holdingsRecords.0"
    }
  },
  "additionalProperties": false,
  "required": [
    "materialTypeId",
    "permanentLoanTypeId",
    "holdingsRecordId"
  ]
}

=== folio-org/mod-inventory-storage/sample-data/bound-with/items/bound-with-item.json
{
  "id" : "f4b8c3d1-f461-4551-aa7b-5f45e64f236c",
  "hrid" : "BW-ITEM-1",
  "status" : {
    "name" : "Available"
  },
  "holdingsRecordId" : "9e8dc8ce-68f3-4e75-8479-d548ce521157",
  "barcode" : "BW-ITEM-1",
  "notes" : [ ],
  "materialTypeId" : "d9acad2f-2aac-4b48-9097-e6ab85906b25",
  "permanentLoanTypeId" : "2b94c631-fca9-4892-a730-03ee529ffe27"
}

=== folio-org/mod-inventory-storage/sample-data/items/semantic-web-primer-90000.json
{
  "id" : "100d10bf-2f06-4aa0-be15-0b95b2d9f9e3",
  "hrid" : "item000000000015",
  "status" : {
    "name" : "Available"
  },
  "formerIds" : [ ],
  "holdingsRecordId" : "e3ff6133-b9a2-4d4c-a1c9-dc1867d4df19",
  "barcode" : "90000",
  "itemLevelCallNumber" : "TK5105.88815 . A58 2004 FT MEADE",
  "enumeration" : "",
  "chronology" : "",
  "copyNumbers" : [ ],
  "notes" : [ ],
  "circulationNotes" : [ ],
  "electronicAccess" : [ {
    "uri" : "http://www.loc.gov/catdir/toc/ecip0718/2007020429.html",
    "linkText" : "Links available",
    "materialsSpecification" : "Table of contents",
    "publicNote" : "Table of contents only",
    "relationshipId" : "3b430592-2e09-4b48-9a0c-0636d66b9fb3"
  } ],
  "statisticalCodeIds" : [ "b5968c9e-cddc-4576-99e3-8e60aed8b0dd" ],
  "materialTypeId": "1a54b431-2e4f-452d-9cae-9cee66c9a892",
  "permanentLoanTypeId" : "2b94c631-fca9-4892-a730-03ee529ffe27",
  "permanentLocationId" :  "fcd64ce1-6995-48f0-840e-89ffa2288371"
}

=== folio-org/mod-inventory-storage/sample-data/bound-with/items/bwit000000001.json
{
  "id" : "6c7196d2-0c2a-4707-a196-ff6b9e84a75e",
  "hrid" : "bwit000000001",
  "status" : {
    "name" : "Available"
  },
  "holdingsRecordId" : "13767c78-f8d0-425e-801d-cc5bd475856a",
  "barcode" : "12",
  "materialTypeId" : "d9acad2f-2aac-4b48-9097-e6ab85906b25",
  "permanentLoanTypeId" : "2b94c631-fca9-4892-a730-03ee529ffe27",
  "tags" : {
    "tagList" : [ "bound-with" ]
  }
}

=== folio-org/mod-inventory-storage/sample-data/items/aba.json
{
  "id": "e9f9bc2f-bad5-4613-9d6c-f55efa5805e7",
  "holdingsRecordId": "684b5dc5-92f6-4db7-b996-b549d88f5e4e",
  "materialTypeId": "615b8413-82d5-4203-aa6e-e37984cb5ac3",
  "permanentLoanTypeId": "a1dc1ce3-d56f-4d8a-b498-d5d674ccc845",
  "status": {
    "name": "Available online"
  },
  "notes": [
    {
      "note": "Print began in 1915. Available in print: Vol. 1 (Jan. 1915)-v. 69, no. 12 (Dec. 1983)."
    }
  ]
}
